In [1]:
import numpy as np

In [2]:
# a. Create a 2D array with random values from 0 to 1
print("(a)")
print()

ARR1 = np.random.rand(3, 4)

print(ARR1)
print()

mean_arr = np.mean(ARR1, axis=1)
std_dev_arr = np.std(ARR1, axis=1)
variance_arr = np.var(ARR1, axis=1)

print("Mean : ", mean_arr)
print("Standard Deviation : ", std_dev_arr)
print("Variance : ", variance_arr)

print()

(a)

[[0.69720883 0.24873758 0.99229429 0.1199161 ]
 [0.96963435 0.38997783 0.78749172 0.608724  ]
 [0.86625037 0.13626146 0.67039575 0.33887831]]

Mean :  [0.5145392  0.68895698 0.50294647]
Standard Deviation :  [0.34928356 0.21465947 0.28346307]
Variance :  [0.121999   0.04607869 0.08035131]



In [3]:
# b. Create a 2D array of size m x n and reshape it
print("(b)")
print()

m = int(input("Enter the number of rows (m): "))
n = int(input("Enter the number of columns (n): "))

ARR2 = np.random.randint(1, 100, size=(m, n))

print()
print("Random Array : \n", ARR2)
print()

print("Shape:", ARR2.shape)
print("Type:", type(ARR2))
print("Data Type:", ARR2.dtype)
print()

ARR2_reshaped = ARR2.reshape((n, m))

print("Reshaped Array : \n", ARR2_reshaped)

print()

(b)


Random Array : 
 [[34 79]
 [ 3 53]]

Shape: (2, 2)
Type: <class 'numpy.ndarray'>
Data Type: int64

Reshaped Array : 
 [[34 79]
 [ 3 53]]



In [4]:
# c. Test elements of an array
print("(c)")
print()

ID_array = np.array([0, 1, 2, 3, np.nan, 5])

is_zero = ID_array == 0
is_non_zero = ID_array != 0
is_nan = np.isnan(ID_array)

zero_indices = np.where(is_zero)[0]
non_zero_indices = np.where(is_non_zero)[0]
nan_indices = np.where(is_nan)[0]

print("Zero Indices : ", zero_indices)
print("Non-Zero Indices : ", non_zero_indices)
print("NAN Indices : ", nan_indices)

print()

(c)

Zero Indices :  [0]
Non-Zero Indices :  [1 2 3 4 5]
NAN Indices :  [4]



In [5]:
# d. Create and perform operations on arrays
print("(d)")
print()

Array1 = np.random.rand(3, 3)
Array2 = np.random.rand(3, 3)
Array3 = np.random.rand(3, 3)

Array4 = Array3 - Array2
Array5 = 2 * Array1

covariance = np.cov(Array1.flatten(), Array4.flatten())[0, 1]
correlation = np.corrcoef(Array1.flatten(), Array5.flatten())[0, 1]

print("Covariance : ", covariance)
print("Correlation : ", correlation)

print()

(d)

Covariance :  -0.06237984206072267
Correlation :  1.0



In [6]:
# e. Sum and product of two arrays
print("(e)")
print()

Array6 = np.random.rand(10)
Array7 = np.random.rand(10)

sum_first_half = np.sum(Array6[:5]) + np.sum(Array7[:5])
product_second_half = np.prod(Array6[5:]) * np.prod(Array7[5:])

print("Sum of First Half of Both Arrays : ", sum_first_half)
print("Product of Second Half of Both Arrays : ", product_second_half)

print()

(e)

Sum of First Half of Both Arrays :  5.06239396459147
Product of Second Half of Both Arrays :  0.00012070136422607078



In [7]:
# f. Size of memory occupied by an array
print("(f)")
print()

Array8 = np.random.rand(100, 100)
memory_size = Array8.nbytes

print("Random Array : ", Array8)
print()

print("Memory Size : ", memory_size)

print()

(f)

Random Array :  [[0.84722038 0.6387215  0.0161146  ... 0.3683099  0.0991431  0.43955842]
 [0.25365117 0.2689119  0.62779609 ... 0.68544872 0.0346554  0.46683944]
 [0.99605006 0.0544433  0.87657948 ... 0.99401566 0.82010613 0.99634576]
 ...
 [0.90565948 0.31705992 0.94000747 ... 0.8460632  0.63151425 0.93452828]
 [0.90603721 0.18426174 0.50774167 ... 0.39382406 0.87163449 0.48258369]
 [0.5688269  0.03867716 0.67491621 ... 0.40699954 0.59960759 0.46259685]]

Memory Size :  80000



In [8]:
# g. Create, manipulate, and store a 2D array
print("(g)")
print()

m = 4
n = 3
Array9 = np.random.randint(10, 100, size=(m, n))

Array9[[0, 1]] = Array9[[1, 0]]
Array9[:, 1] = np.flip(Array9[:, 1])

Array10 = Array9.copy()

print("Random Array : ", Array9)

print("Array with Rows Swapped and Column Reversed : ", Array10)

(g)

Random Array :  [[31 56 32]
 [32 55 29]
 [23 78 60]
 [98 48 62]]
Array with Rows Swapped and Column Reversed :  [[31 56 32]
 [32 55 29]
 [23 78 60]
 [98 48 62]]
